name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  VCPKG_BINARY_SOURCES: clear;http,https://vcpkg-obs.kaito.tokyo/binarycache/{name}/{version}/{sha}
  VCPKG_ROOT: ${{ github.workspace }}/vcpkg

permissions:
  contents: read

jobs:
  TestOnMacOS:
    runs-on: macos-15
    timeout-minutes: 30

    steps:
      - name: Checkout project repository
        uses: actions/checkout@v5

      - name: Checkout vcpkg repository
        uses: actions/checkout@v5
        with:
          repository: microsoft/vcpkg
          path: ${{ env.VCPKG_ROOT }}

      - name: Bootstrap vcpkg
        working-directory: ${{ env.VCPKG_ROOT }}
        run: ./bootstrap-vcpkg.sh

      - name: Install dependencies from vcpkg
        run: .github/scripts/install-vcpkg-macos.bash

      - name: Configure
        run: cmake --preset macos

      - name: Build
        run: cmake --build --preset macos

      - name: Run tests
        run: ctest --preset macos --verbose

  TestOnWindows:
    runs-on: windows-2022
    timeout-minutes: 30

    steps:
      - name: Checkout project repository
        uses: actions/checkout@v5

      - name: Checkout vcpkg repository
        uses: actions/checkout@v5
        with:
          repository: microsoft/vcpkg
          path: ${{ env.VCPKG_ROOT }}

      - name: Bootstrap vcpkg
        working-directory: ${{ env.VCPKG_ROOT }}
        shell: pwsh
        run: .\bootstrap-vcpkg.bat

      - name: Install dependencies from vcpkg
        run: $VCPKG_ROOT/vcpkg install --triplet x64-windows-static-md-obs

      - name: Configure
        run: cmake --preset windows-x64

      - name: Build
        run: cmake --build --preset windows-x64

      - name: Run tests
        run: ctest --preset windows-x64 --verbose

  TestOnUbuntu:
    runs-on: ubuntu-24.04
    timeout-minutes: 30

    steps:
      - name: Checkout project repository
        uses: actions/checkout@v5

      - name: Checkout vcpkg repository
        uses: actions/checkout@v5
        with:
          repository: microsoft/vcpkg
          path: ${{ env.VCPKG_ROOT }}

      - name: Bootstrap vcpkg
        working-directory: ${{ env.VCPKG_ROOT }}
        run: ./bootstrap-vcpkg.sh

      - name: Install system dependencies on Ubuntu
        run: |
          echo "man-db man-db/auto-update boolean false" | sudo debconf-set-selections
          sudo apt-get remove --purge -y man-db
          sudo add-apt-repository -y ppa:obsproject/obs-studio
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential \
            libgles2-mesa-dev \
            libsimde-dev \
            obs-studio \
            qt6-base-dev \
            libqt6svg6-dev \
            qt6-base-private-dev \
            cmake \
            git \
            jq \
            ninja-build \
            pkg-config \
            libgtest-dev

      - name: Install dependencies from vcpkg
        run: $VCPKG_ROOT/vcpkg install --triplet x64-linux-obs --debug

      - name: Configure
        run: cmake --preset ubuntu-x86_64

      - name: Build
        run: cmake --build --preset ubuntu-x86_64

      - name: Run tests
        run: ctest --preset ubuntu-x86_64 --verbose
