name: Unsupported Build

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  BuildOnArch:
    runs-on: ubuntu-24.04

    timeout-minutes: 30

    container:
      image: archlinux:base-devel

    steps:
      - name: Checkout project repository
        uses: actions/checkout@v5

      - name: Setup builder
        run: |
          useradd -m builder
          echo 'builder ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/builder
          chown -R builder:builder .
          pacman -Sy --noconfirm git

      - name: Install cpp-httplib
        run: |
          sudo -u builder git clone https://aur.archlinux.org/cpp-httplib.git
          cd cpp-httplib
          sudo -u builder makepkg -si --noconfirm

      - name: Build
        working-directory: unsupported/arch/live-stream-segmenter
        run: sudo -u builder makepkg -s --noconfirm

  BuildOnArchGit:
    runs-on: ubuntu-24.04

    timeout-minutes: 30

    container:
      image: archlinux:base-devel

    steps:
      - name: Checkout project repository
        uses: actions/checkout@v5

      - name: Setup builder
        run: |
          useradd -m builder
          echo 'builder ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/builder
          chown -R builder:builder .
          pacman -Sy --noconfirm git

      - name: Install cpp-httplib
        run: |
          sudo -u builder git clone https://aur.archlinux.org/cpp-httplib.git
          cd cpp-httplib
          sudo -u builder makepkg -si --noconfirm

      - name: Build
        working-directory: unsupported/arch/live-stream-segmenter-git
        run: sudo -u builder makepkg -s --noconfirm

  BuildFlatpak:
    runs-on: ubuntu-24.04

    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:kde-6.8
      options: --privileged

    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@10a3c29f0162516f0f68006be14c92f34bd4fa6c
        with:
          bundle: com.obsproject.Studio.Plugin.LiveStreamSegmenter
          manifest-path: unsupported/flatpak/com.obsproject.Studio.Plugin.LiveStreamSegmenter.json
          cache-key: flatpak-builder-${{ github.sha }}
