name: Unsupported Build

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-arch:
    name: Build on Arch Linux

    runs-on: ubuntu-24.04
    timeout-minutes: 30

    container:
      image: archlinux:base-devel

    permissions:
      contents: read

    steps:
      - name: Checkout project repository
        uses: actions/checkout@v6

      - name: Setup builder
        shell: bash
        run: |
          useradd -m builder
          echo 'builder ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/builder
          chown -R builder:builder .
          pacman -Syu --noconfirm git

      - name: Install cpp-httplib
        run: |
          sudo -u builder git clone https://aur.archlinux.org/cpp-httplib.git
          cd cpp-httplib
          sudo -u builder makepkg -si --noconfirm

      - name: Build
        shell: bash
        working-directory: unsupported/arch/live-stream-segmenter
        run: sudo -u builder makepkg -s --noconfirm

  build-arch-git:
    name: Build on Arch Linux (Git Version)

    runs-on: ubuntu-24.04
    timeout-minutes: 30

    permissions:
      contents: read

    container:
      image: archlinux:base-devel

    steps:
      - name: Checkout project repository
        uses: actions/checkout@v6

      - name: Setup builder
        shell: bash
        run: |
          useradd -m builder
          echo 'builder ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/builder
          chown -R builder:builder .
          pacman -Syu --noconfirm git

      - name: Install cpp-httplib
        run: |
          sudo -u builder git clone https://aur.archlinux.org/cpp-httplib.git
          cd cpp-httplib
          sudo -u builder makepkg -si --noconfirm

      - name: Build
        shell: bash
        working-directory: unsupported/arch/live-stream-segmenter-git
        run: sudo -u builder makepkg -s --noconfirm

  build-flatpak:
    name: Build Flatpak

    runs-on: ubuntu-24.04
    timeout-minutes: 30

    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:kde-6.8
      options: --privileged

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@10a3c29f0162516f0f68006be14c92f34bd4fa6c
        with:
          bundle: com.obsproject.Studio.Plugin.LiveStreamSegmenter
          manifest-path: unsupported/flatpak/com.obsproject.Studio.Plugin.LiveStreamSegmenter.json
          cache-key: flatpak-builder-${{ github.sha }}
